config/routes.rb
Rails.application.routes.draw do
  root 'repos#index'
  get :search, to: 'repos#search'

  resources :repos, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repos_controller.rb
require 'github_api_handler.rb'

class ReposController < ApplicationController
  before_action :search_props

  def index
  end

  def search
    (res, err) = GithubApiHandler.get_repositories(params[:q])
    @errors << err

    if res.present?
      res_body = JSON.parse(res.body)
      @repos += res_body['items']
      @errors << 'No repositories were found' if res_body['total_count'].zero?
    end

    render template: 'repos/index', assigns: { repos: @repos, errors: @errors }
  end

  private

  def search_props
    @errors ||= []
    @repos ||= []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv":"Content-Type"}/
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %title Github Repos
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/repos/_repo.html.haml
%li.card
  = link_to repo['html_url'] do
    = image_tag repo['owner']['avatar_url'], class: 'card-img'
  %h4.repo_name
    = link_to repo['full_name'], repo['html_url']

  %ul.no-bullet.body-text
    %li
      = repo['watchers_count']
      = 'watchers'.pluralize(repo['watchers_count'])
    %li
      = repo['stargazers_count']
      = 'stars'.pluralize(repo['stargazers_count'])
    %li
      = repo['forks_count']
      = 'forks'.pluralize(repo['forks_count'])
    %li
      = repo['open_issues_count']
      = 'open issues'.pluralize(repo['open_issues_count'])

app/views/repos/_search.html.haml
= form_tag(search_path, method: :get, role: 'form') do
  %formset
    = text_field_tag :q, params[:q], placeholder: 'Search for a github repo'
    = button_tag 'Search repos', class: 'search-button'

app/views/repos/index.html.haml
%main
  %header
    %h1= link_to 'Github Repos', '/'

  = render partial: 'repos/search'

  %section#results
    = render partial: 'shared/errors', locals: { errors: @errors.compact }

    %ul#results-table.no-bullet
      - @repos.compact.each do |repo|
        = render partial: 'repos/repo', locals: { repo: repo }

app/views/shared/_errors.html.haml
- if errors.any?
  %section#errors
    - errors.each do |error|
      %p= error